# Generated by Django 4.2 on 2023-04-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_hour', models.TimeField(verbose_name='Heure de début')),
                ('end_hour', models.TimeField(verbose_name='Heure de fin')),
                ('day_of_week', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=15, verbose_name='Jour de la semaine')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_classes.course', verbose_name='subject')),
                ('schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_classes.schoolclass', verbose_name='schoolclass')),
            ],
            options={
                'verbose_name': 'Timeslot',
                'verbose_name_plural': 'Timeslots',
            },
        ),
    ]
