# Generated by Django 4.2 on 2023-04-17 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0005_alter_establishmenttype_name'),
        ('gestion_emplois_temps', '0002_timeslot_created_at_timeslot_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_hour',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de début'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.establishment', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_emplois_temps.room', verbose_name='room'),
        ),
    ]
