# Generated by Django 4.2 on 2023-04-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_emplois_temps', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('room', 'start_datetime', 'end_datetime')},
        ),
    ]
