# Generated by Django 4.2 on 2023-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('MATH', 'Mathématiques'), ('PHYS', 'Physique'), ('CHIM', 'Chimie'), ('BIO', 'Biologie'), ('HIST', 'Histoire'), ('GEO', 'Géographie')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('MAT1', 'MATERNELLE 1'), ('MAT2', 'MATERNELLE 2'), ('C1', 'PRIMAIRE C1'), ('CP', 'PRIMAIRE CP'), ('CE1', 'PRIMAIRE CE1'), ('CE2', 'PRIMAIRE CE2'), ('CM1', 'PRIMAIRE CM1'), ('CM2', 'PRIMAIRE CM2'), ('6EME', 'SECONDAIRE 6EME'), ('5EME', 'SECONDAIRE 5EME'), ('4EME', 'SECONDAIRE 4EME'), ('3EME', 'SECONDAIRE 3EME'), ('2ND', 'SECONDAIRE 2ND'), ('1ERE', 'SECONDAIRE 1ERE'), ('TERMINAL', 'SECONDAIRE TERMINAL'), ('L1', 'UNIVERSITAIRE LICENCE1'), ('L2', 'UNIVERSITAIRE LICENCE2'), ('L3', 'UNIVERSITAIRE LICENCE3'), ('M1', 'UNIVERSITAIRE MASTER1'), ('M2', 'UNIVERSITAIRE MASTER2')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
    ]
