# Generated by Django 4.2 on 2023-04-14 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles': 'HEAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_establishments', to=settings.AUTH_USER_MODEL),
        ),
    ]
