# Generated by Django 4.2 on 2023-04-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_alter_establishment_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmenttype',
            name='name',
            field=models.CharField(choices=[('PRESCHOOL', 'Preschool'), ('PRIMARY', 'Primary'), ('MIDDLE_SCHOOL', 'Middle School'), ('HIGH_SCHOOL', 'High School'), ('UNIVERSITY', 'University'), ('INSTITUTE', 'Institute'), ('TRAINING_CENTER', 'Training Center')], max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
