# Generated by Django 4.2 on 2023-04-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_points', models.PositiveIntegerField(verbose_name='Total Points')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_obtained', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Points Obtained')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_evaluations.assessment', verbose_name='Assessment')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_evaluations.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
            },
        ),
    ]
