# Generated by Django 4.2 on 2023-04-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_alter_establishment_head'),
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etablissements.establishment', verbose_name='Establishment'),
        ),
    ]
